// Venues data — based on the existing intheevent.com/venues page,
// expanded with realistic detail for an interior venue catalog.

const VENUES = [
  // FEATURED venue (rendered separately at top)
  {
    id: 'grand-america',
    name: 'The Grand America Hotel',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '555 S Main St, Salt Lake City, UT 84111',
    photo: 'assets/photos/v-grand-america.jpg',
    style: 'Luxury Ballroom',
    capacity: '1,200',
    sqft: '24,000 sq ft',
    ceiling: "21' clear",
    powerNote: '3-phase, generator-ready',
    desc: 'Five-star European-styled property anchoring downtown Salt Lake. The Grand Ballroom seats 1,200 for plated dinners and pairs with seven satellite ballrooms for breakouts, gala receptions, and multi-day conferences. We have rigged, staged, and floraled this room more than fifty times.',
    galleryStyles: ['v-grand-america.jpg', 'v-uccu-center.jpg', 'v-uvu-evergrowing.jpg', 'v-monson-center.jpg'],
    featured: true,
  },

  {
    id: 'salt-palace',
    name: 'Salt Palace Convention Center',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '100 SW Temple, Salt Lake City, UT 84101',
    photo: 'assets/photos/v-salt-palace.jpg',
    style: 'Convention Center',
    capacity: '5,000+',
    sqft: '515,000 sq ft',
    ceiling: "30' clear",
    desc: 'Utah\u2019s flagship convention space. We program the Salt Palace dozens of times a year — main stage, breakouts, exhibit halls, and outdoor activations on the plaza.',
  },
  {
    id: 'monson-center',
    name: 'The Thomas S. Monson Center',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '411 E South Temple, Salt Lake City, UT 84111',
    photo: 'assets/photos/v-monson-center.jpg',
    style: 'Historic Mansion',
    capacity: '180',
    sqft: '6,400 sq ft',
    ceiling: "14' parlor",
    desc: 'Restored 1898 mansion with intimate parlors, a grand staircase, and a tented south lawn. Ideal for board dinners, private receptions, and editorial brand activations.',
  },
  {
    id: 'uccu-center',
    name: 'UCCU Center',
    city: 'Orem, UT',
    region: 'utah-county',
    address: '800 W University Pkwy, Orem, UT 84058',
    photo: 'assets/photos/v-uccu-center.jpg',
    style: 'Arena',
    capacity: '8,500',
    sqft: 'Arena floor + concourse',
    ceiling: "55' grid",
    desc: 'UVU\u2019s 8,500-seat arena. Black-out capable for full theatrical galas — we transformed the room for the President\u2019s Scholarship Ball with crystal rigging and a 360° runway.',
  },
  {
    id: 'kingsbury-hall',
    name: 'Kingsbury Hall',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '1395 Presidents Cir, Salt Lake City, UT 84112',
    photo: 'assets/photos/v-kingsbury-hall.jpg',
    style: 'Theater',
    capacity: '1,900',
    sqft: 'Proscenium house',
    ceiling: "Fly tower",
    desc: 'University of Utah\u2019s historic proscenium theater. House lighting, fly tower, and orchestra pit make this a natural fit for keynotes, performances, and award shows.',
  },
  {
    id: 'st-regis-deer-valley',
    name: 'St. Regis Deer Valley',
    city: 'Park City, UT',
    region: 'mountain',
    address: '2300 Deer Valley Dr E, Park City, UT 84060',
    photo: 'assets/photos/v-naiop.jpg',
    style: 'Mountain Resort',
    capacity: '400',
    sqft: '14,000 sq ft indoor + decks',
    ceiling: "18' great room",
    desc: 'Slope-side luxury with a vaulted great room, multiple terraces, and unforgettable winter views. We\u2019ve produced executive retreats and weddings here through every season.',
  },
  {
    id: 'montage-deer-valley',
    name: 'Montage Deer Valley',
    city: 'Park City, UT',
    region: 'mountain',
    address: '9100 Marsac Ave, Park City, UT 84060',
    photo: 'assets/photos/v-uvu-evergrowing.jpg',
    style: 'Mountain Resort',
    capacity: '650',
    sqft: '22,000 sq ft',
    ceiling: "20'",
    desc: 'Empire Pass mountain resort with the largest ballroom in Park City. We rig and floral the Empire Ballroom for galas and conferences nationally.',
  },
  {
    id: 'waldorf-park-city',
    name: 'Waldorf Astoria Park City',
    city: 'Park City, UT',
    region: 'mountain',
    address: '2100 W Frostwood Blvd, Park City, UT 84098',
    photo: 'assets/photos/venue-waldorf-park-city.jpg',
    style: 'Mountain Resort',
    capacity: '300',
    sqft: '8,200 sq ft',
    ceiling: "16'",
    desc: 'Canyons-side property at the base of the gondola. Polished ballroom, exterior plazas, and a private lounge — strong for incentive trips and brand summits.',
  },
  {
    id: 'stein-eriksen',
    name: 'Stein Eriksen Lodge',
    city: 'Park City, UT',
    region: 'mountain',
    address: '7700 Stein Way, Park City, UT 84060',
    photo: 'assets/photos/venue-stein-eriksen.jpg',
    style: 'Mountain Lodge',
    capacity: '350',
    sqft: '10,500 sq ft',
    ceiling: "Vaulted timber",
    desc: 'Norwegian-style mountain lodge with timber-framed ballrooms and Silver Lake views. A perennial favorite for incentive groups and intimate galas.',
  },
  {
    id: 'snowbasin',
    name: 'Snowbasin Resort',
    city: 'Huntsville, UT',
    region: 'mountain',
    address: '3925 Snow Basin Rd, Huntsville, UT 84317',
    photo: 'assets/photos/v-snowbasin.jpg',
    style: 'Ski Resort',
    capacity: '900',
    sqft: 'Needles Lodge + base',
    ceiling: "Open timber",
    desc: 'Olympic-legacy ski resort. Mid-mountain Needles Lodge unlocks a gondola-arrival reception unlike anything else in the state.',
  },
  {
    id: 'four-seasons-jackson',
    name: 'Four Seasons Jackson Hole',
    city: 'Jackson, WY',
    region: 'mountain',
    address: '7680 Granite Loop Rd, Teton Village, WY 83025',
    photo: 'assets/photos/venue-four-seasons-jackson.jpg',
    style: 'Mountain Resort',
    capacity: '500',
    sqft: '12,000 sq ft',
    ceiling: "22' great room",
    desc: 'Teton Village luxury, walking distance to the tram. We travel a full crew for incentive groups, brand summits, and destination weddings.',
  },
  {
    id: 'amangani',
    name: 'Amangani',
    city: 'Jackson, WY',
    region: 'mountain',
    address: '5000 N Spring Gulch Rd, Jackson, WY 83001',
    photo: 'assets/photos/venue-amangani.jpg',
    style: 'Resort',
    capacity: '180',
    sqft: 'Indoor + butte terrace',
    ceiling: "Stone + glass",
    desc: 'Sandstone resort perched on a butte over Jackson Hole. Intimate scale, cinematic horizon — perfect for executive retreats and small destination events.',
  },
  {
    id: 'sundance',
    name: 'Sundance Mountain Resort',
    city: 'Sundance, UT',
    region: 'mountain',
    address: 'N Fork Rd 8841, Sundance, UT 84604',
    photo: 'assets/photos/v-stgeorge.jpg',
    style: 'Mountain Resort',
    capacity: '450',
    sqft: 'Tree Room + decks',
    ceiling: 'Open timber',
    desc: 'Robert Redford\u2019s artist-driven retreat at the base of Mount Timpanogos. Multiple intimate venues spread across a creek-side campus.',
  },
];

window.VENUES = VENUES;
