// Venues data — intheevent.com/venues full catalog
// Addresses sourced from live site screenshots; specs researched or estimated by venue type.
// Photos are placeholders — replace paths in assets/photos/ before launch.

const VENUES = [
  // ── FEATURED ────────────────────────────────────────────────
  {
    id: 'grand-america',
    name: 'The Grand America Hotel',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '555 S Main St, Salt Lake City, UT 84111',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/GrandAmerica1.png',
    style: 'Luxury Ballroom',
    capacity: '1,200',
    sqft: '24,000 sq ft',
    ceiling: "21' clear",
    powerNote: '3-phase, generator-ready',
    desc: 'Five-star European-styled property anchoring downtown Salt Lake. The Grand Ballroom seats 1,200 for plated dinners and pairs with seven satellite ballrooms for breakouts, gala receptions, and multi-day conferences. We have rigged, staged, and floraled this room more than fifty times.',
    galleryStyles: ['v-grand-america.jpg', 'v-uccu-center.jpg', 'v-uvu-evergrowing.jpg', 'v-monson-center.jpg'],
    featured: true,
  },

  // ── SLC — CONVENTION ────────────────────────────────────────
  {
    id: 'salt-palace',
    name: 'Salt Palace Convention Center',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '90 SW Temple, Salt Lake City, UT 84101',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/SaltPalaceConventionCenter2-scaled.jpg',
    style: 'Convention Center',
    capacity: '5,000+',
    sqft: '515,000 sq ft',
    ceiling: "30' clear",
    desc: "Utah's flagship convention space. We program the Salt Palace dozens of times a year — main stage, breakouts, exhibit halls, and outdoor activations on the plaza.",
  },

  // ── SLC — HOTELS ────────────────────────────────────────────
  {
    id: 'hyatt-regency',
    name: 'Hyatt Regency Salt Lake City',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '170 S West Temple St, Salt Lake City, UT 84101',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/HyattRegency2.jpg',
    style: 'Convention Hotel',
    capacity: '2,875',
    sqft: '60,000 sq ft',
    ceiling: "22' Regency Ballroom",
    desc: "Downtown SLC's newest convention hotel, connected to the Salt Palace. The Regency Ballroom spans 23,000 sq ft and pairs with 30 breakout rooms for multi-day conferences and signature galas.",
  },
  {
    id: 'little-america',
    name: 'Little America Hotel',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '500 South Main St, Salt Lake City, UT 84101',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/LittleAmerica1.jpg',
    style: 'Full-Service Hotel',
    capacity: '1,200',
    sqft: '28,000 sq ft',
    ceiling: "16' ballroom",
    desc: 'Beloved SLC landmark with a grand ballroom, multiple salons, and garden courtyards. A reliable production partner for corporate dinners, award shows, and holiday galas.',
  },
  {
    id: 'hilton-city-center',
    name: 'Hilton Salt Lake City Center',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '255 S West Temple, Salt Lake City, UT 84101',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/SLC_Hilton1.jpg',
    style: 'Convention Hotel',
    capacity: '1,000',
    sqft: '25,000 sq ft',
    ceiling: "20' main hall",
    desc: 'High-capacity downtown property two blocks from the Salt Palace. Grand Ballroom and multi-room pre-function space ideal for breakout-heavy conferences and awards evenings.',
  },
  {
    id: 'le-meridien',
    name: 'Le Méridien Salt Lake City',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '131 S 300 W, Salt Lake City, UT 84101',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/LeMeridien1.jpeg',
    style: 'Boutique Hotel',
    capacity: '350',
    sqft: '12,000 sq ft',
    ceiling: "14' ballroom",
    desc: "Modern European-inspired hotel in downtown's creative core. Intimate ballroom, art-forward lobby, and rooftop terrace make it a favorite for brand activations and executive dinners.",
  },
  {
    id: 'marriott-downtown',
    name: 'Salt Lake Marriott Downtown',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '75 South West Temple, Salt Lake City, UT 84101',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/MarriottDowntown1.jpeg',
    style: 'Full-Service Hotel',
    capacity: '800',
    sqft: '21,000 sq ft',
    ceiling: "18' ballroom",
    desc: 'Downtown anchor with a versatile ballroom and rooftop social spaces. Strong AV infrastructure and proximity to the convention district make it a proven conference hotel.',
  },
  {
    id: 'hotel-monaco',
    name: 'Hotel Monaco Salt Lake City',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '15 W 200 S, Salt Lake City, UT 84101',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/HotelMonaco2.jpg',
    style: 'Boutique Hotel',
    capacity: '250',
    sqft: '6,000 sq ft',
    ceiling: "12' ballroom",
    desc: 'Eclectic Kimpton boutique hotel in a restored 1924 Continental Bank building. Intimate ballrooms and a dramatic lobby set the stage for receptions, brand dinners, and small conferences.',
  },
  {
    id: 'radisson-slc',
    name: 'Radisson Hotel Salt Lake City',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '215 S Temple, Salt Lake City, UT 84101',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/RadissonHotel.jpeg',
    style: 'Full-Service Hotel',
    capacity: '600',
    sqft: '14,000 sq ft',
    ceiling: "16' ballroom",
    desc: 'Full-service hotel steps from Temple Square. Reliable ballroom footprint and central location make it a workhorse venue for corporate meetings, award luncheons, and receptions.',
  },
  {
    id: 'asher-adams',
    name: 'Asher Adams Hotel',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '2 400 W, Salt Lake City, UT 84101',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/AsherAdams.jpeg',
    style: 'Autograph Collection Hotel',
    capacity: '400',
    sqft: '10,000 sq ft',
    ceiling: "Restored train station atrium",
    desc: 'Historic Union Pacific rail station reborn as a Marriott Autograph Collection hotel. Barrel-vaulted ceilings, original terrazzo floors, and contemporary event spaces create a cinematic backdrop near the airport corridor.',
  },

  // ── SLC — ARTS & CULTURE ────────────────────────────────────
  {
    id: 'kingsbury-hall',
    name: 'Kingsbury Hall',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '1395 Presidents Cir, Salt Lake City, UT 84112',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/KingsburyHall1.jpg',
    style: 'Theater',
    capacity: '1,900',
    sqft: 'Proscenium house',
    ceiling: "Fly tower",
    desc: "University of Utah's historic proscenium theater. House lighting, fly tower, and orchestra pit make this a natural fit for keynotes, performances, and award shows.",
  },
  {
    id: 'capitol-theatre',
    name: 'Capitol Theatre',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '50 W 200 South, Salt Lake City, UT 84101',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/CapitolTheatre.jpeg',
    style: 'Historic Theater',
    capacity: '1,800',
    sqft: 'Proscenium house',
    ceiling: 'Fly tower',
    desc: 'Beautifully restored 1913 theater in the heart of downtown SLC. Grand lobby, ornate proscenium, and full fly tower — ideal for keynotes, award ceremonies, and theatrical galas.',
  },
  {
    id: 'rose-wagner',
    name: 'Rose Wagner Performing Arts Center',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '138 West 300 South, Salt Lake City, UT 84101',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/RoseWagner.jpg',
    style: 'Performing Arts Center',
    capacity: '500',
    sqft: 'Multi-stage complex',
    ceiling: "Black-box grid",
    desc: 'Three intimate performance spaces in one building — black box, proscenium, and studio. Flexible for intimate brand events, film screenings, and panel-format conferences.',
  },
  {
    id: 'hale-centre',
    name: 'Hale Centre Theatre',
    city: 'West Valley City, UT',
    region: 'slc',
    address: '3333 South Decker Lake Drive, West Valley City, UT 84119',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/HaleCenter.jpg',
    style: 'Theater',
    capacity: '900',
    sqft: 'Theater in the round',
    ceiling: "Theatrical grid",
    desc: 'Award-winning theater-in-the-round with state-of-the-art staging. The intimate configuration and superior sightlines make it uniquely suited for immersive brand experiences and staged corporate productions.',
  },
  {
    id: 'monson-center',
    name: 'The Thomas S. Monson Center',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '411 E South Temple, Salt Lake City, UT 84111',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/MonsonCenter.jpg',
    style: 'Historic Mansion',
    capacity: '180',
    sqft: '6,400 sq ft',
    ceiling: "14' parlor",
    desc: 'Restored 1898 mansion with intimate parlors, a grand staircase, and a tented south lawn. Ideal for board dinners, private receptions, and editorial brand activations.',
  },
  {
    id: 'natural-history-museum',
    name: 'Natural History Museum of Utah',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '301 Wakara Way, Salt Lake City, UT 84108',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/NaturalHistoryMuseum.jpeg',
    style: 'Museum',
    capacity: '1,200',
    sqft: '15,000 sq ft rentable',
    ceiling: "Atrium + galleries",
    desc: 'Award-winning copper-clad museum perched above the valley with panoramic mountain views. Dinosaur halls, canyon galleries, and a dramatic atrium create unforgettable event backdrops.',
  },
  {
    id: 'red-butte-garden',
    name: 'Red Butte Garden',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '300 Wakara Way, Salt Lake City, UT 84108',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/RedButteGarden.jpg',
    style: 'Botanical Garden',
    capacity: '5,000',
    sqft: '100-acre estate',
    ceiling: 'Open sky',
    desc: 'The Wasatch foothills as your backdrop. Terraced gardens, stone pavilion, and an outdoor amphitheater host summer receptions, charity galas, and brand activations under the stars.',
  },

  // ── SLC — EVENT VENUES ──────────────────────────────────────
  {
    id: 'gallivan-center',
    name: 'Gallivan Center',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '50 E 200 S, Salt Lake City, UT 84111',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/GallivanCenter.jpg',
    style: 'Urban Plaza',
    capacity: '3,000',
    sqft: 'Open-air plaza + amphitheater',
    ceiling: 'Open sky',
    desc: "Downtown SLC's premier outdoor event plaza, steps from the TRAX stop. Open-air stage, grass lawn, and surrounding hardscape handle concerts, festivals, and corporate outdoor activations.",
  },
  {
    id: 'the-complex',
    name: 'The Complex',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '536 West 100 South, Salt Lake City, UT 84101',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/TheComplex.jpg',
    style: 'Concert & Event Venue',
    capacity: '1,500',
    sqft: '18,000 sq ft',
    ceiling: "26' clear",
    desc: "SLC's most flexible large-format event space — a former industrial complex with two main rooms, rooftop bar, and production-ready rigging and power infrastructure.",
  },
  {
    id: 'union-event-center',
    name: 'The Union Event Center',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '235 North 500 West, Salt Lake City, UT 84116',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/UnionEventCenter-scaled.jpg',
    style: 'Ballroom',
    capacity: '1,800',
    sqft: '22,000 sq ft',
    ceiling: "20' ballroom",
    desc: 'Elegant ballroom venue north of downtown with a sweeping domed ceiling and hardwood floors. One of the most beautiful dedicated ballroom spaces in the region for galas and corporate dinners.',
  },
  {
    id: 'falls-event-center',
    name: 'The Falls Event Center',
    city: 'Salt Lake City, UT',
    region: 'slc',
    address: '580 South 600 East, Salt Lake City, UT 84102',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/FallsEventCenter.jpg',
    style: 'Ballroom',
    capacity: '500',
    sqft: '10,000 sq ft',
    ceiling: "14' ballroom",
    desc: 'Turn-key ballroom venue with an elegant décor package, in-house catering coordination, and flexible layout for receptions, galas, and corporate events.',
  },

  // ── UTAH COUNTY ─────────────────────────────────────────────
  {
    id: 'uccu-center',
    name: 'UCCU Center',
    city: 'Orem, UT',
    region: 'utah-county',
    address: '800 W University Pkwy, Orem, UT 84058',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/UCCU_Arena.png',
    style: 'Arena',
    capacity: '8,500',
    sqft: 'Arena floor + concourse',
    ceiling: "55' grid",
    desc: "UVU's 8,500-seat arena. Black-out capable for full theatrical galas — we transformed the room for the President's Scholarship Ball with crystal rigging and a 360° runway.",
  },
  {
    id: 'utah-valley-convention',
    name: 'Utah Valley Convention Center',
    city: 'Provo, UT',
    region: 'utah-county',
    address: '220 W Center St, Provo, UT 84601',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/UtahValleyConventionCenter.jpg',
    style: 'Convention Center',
    capacity: '2,000',
    sqft: '83,578 sq ft',
    ceiling: "32' exhibit hall",
    desc: "Utah County's premier convention facility with mountain views. The Grand Ballroom seats 1,000 for galas; combined with a 19,600 sq ft exhibit hall it anchors major regional conferences and trade shows.",
  },
  {
    id: 'thanksgiving-point',
    name: 'Thanksgiving Point',
    city: 'Lehi, UT',
    region: 'utah-county',
    address: '3003 Thanksgiving Way, Lehi, UT 84043',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/ThanksgivingPoint.jpg',
    style: 'Event Campus',
    capacity: '3,000+',
    sqft: '55-acre grounds',
    ceiling: "Pavilion + outdoor",
    desc: 'Fifty-five acres of manicured gardens, multiple indoor event halls, and a farm-themed venue campus. Handles everything from a 50-person board dinner to a 3,000-guest outdoor festival.',
  },
  {
    id: 'viridian-event-center',
    name: 'Viridian Event Center',
    city: 'West Jordan, UT',
    region: 'slc',
    address: '8030 South 1825 West, West Jordan, UT 84088',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/ViridianEventCenter.jpg',
    style: 'Event Center',
    capacity: '1,800',
    sqft: '35,000 sq ft',
    ceiling: "28' main hall",
    desc: "South Valley's leading event center with a clear-span main hall, divisible ballroom, and extensive pre-function space. Strong rigging points and power make it a technical production favorite.",
  },
  {
    id: 'scera-theater',
    name: 'SCERA Theater',
    city: 'Orem, UT',
    region: 'utah-county',
    address: '745 South State Street, Orem, UT 84058',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/SCERA_Center.jpg',
    style: 'Performing Arts Center',
    capacity: '600',
    sqft: 'Theater + lobby',
    ceiling: "Theatrical grid",
    desc: "Orem's beloved community arts center with a proscenium theater, lobby, and outdoor shell amphitheater. Versatile for keynotes, award shows, concerts, and cultural galas.",
  },

  // ── MOUNTAIN — COTTONWOOD CANYONS ───────────────────────────
  {
    id: 'snowbird',
    name: 'Snowbird Resort',
    city: 'Snowbird, UT',
    region: 'mountain',
    address: '9385 Snowbird Center Trail, Snowbird, UT 84092',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/Snowbird.jpg',
    style: 'Mountain Resort',
    capacity: '1,200',
    sqft: '80,000 sq ft',
    ceiling: "16' Cliff Ballroom + aerial tram",
    desc: 'Year-round mountain resort at the top of Little Cottonwood Canyon. The iconic Cliff Lodge, aerial tram arrival, and alpine meadows create a production canvas unlike anywhere in the Wasatch.',
  },
  {
    id: 'snowpine-lodge',
    name: 'Snowpine Lodge',
    city: 'Alta, UT',
    region: 'mountain',
    address: '10420 Little Cottonwood Rd, Alta, UT 84092',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/SnowpineLodge.jpg',
    style: 'Mountain Lodge',
    capacity: '200',
    sqft: '5,000 sq ft',
    ceiling: "Vaulted timber",
    desc: 'Boutique alpine lodge at the base of Alta ski area. Intimate and refined — the perfect setting for executive retreats, incentive dinners, and small destination events.',
  },
  {
    id: 'solitude',
    name: 'Solitude Mountain Resort',
    city: 'Solitude, UT',
    region: 'mountain',
    address: '12000 Big Cottonwood Canyon Rd, Solitude, UT 84121',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/Solitude.jpg',
    style: 'Mountain Resort',
    capacity: '800',
    sqft: 'Inn + base lodge',
    ceiling: "Vaulted timber",
    desc: 'Quiet and exclusive Big Cottonwood Canyon resort. The Inn at Solitude and ski-beach terrace offer a genuine mountain-village feel for incentive groups and intimate destination events.',
  },
  {
    id: 'snowbasin',
    name: 'Snowbasin Resort',
    city: 'Huntsville, UT',
    region: 'mountain',
    address: '3925 Snow Basin Rd, Huntsville, UT 84317',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/Snowbasin.jpg',
    style: 'Ski Resort',
    capacity: '900',
    sqft: 'Needles Lodge + base',
    ceiling: "Open timber",
    desc: 'Olympic-legacy ski resort. Mid-mountain Needles Lodge unlocks a gondola-arrival reception unlike anything else in the state.',
  },

  // ── MOUNTAIN — HEBER / MIDWAY ───────────────────────────────
  {
    id: 'zermatt',
    name: 'Zermatt Resort',
    city: 'Midway, UT',
    region: 'mountain',
    address: '784 W Resort Dr, Midway, UT 84049',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/Zermatt.jpg',
    style: 'Mountain Resort',
    capacity: '1,500',
    sqft: '65,000 sq ft',
    ceiling: "18' ballroom",
    desc: "Swiss-themed resort in Midway's pastoral Heber Valley. Eighteen distinct event spaces totaling 65,000 sq ft — the largest dedicated event facility between SLC and Park City.",
  },
  {
    id: 'homestead-resort',
    name: 'Homestead Resort',
    city: 'Midway, UT',
    region: 'mountain',
    address: '700 Homestead Dr, Midway, UT 84049',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/Homestead.jpg',
    style: 'Historic Resort',
    capacity: '600',
    sqft: '18,000 sq ft',
    ceiling: "14' ballroom",
    desc: "Utah's oldest resort, anchored by a famous hot spring crater. Charming barn venues, garden spaces, and a grand ballroom — ideal for Western-themed galas and corporate retreats.",
  },
  {
    id: 'soldier-hollow',
    name: 'Soldier Hollow',
    city: 'Midway, UT',
    region: 'mountain',
    address: '2002 Olympic Drive, Midway, UT 84049',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/SoldierHollow.jpg',
    style: 'Olympic Venue',
    capacity: '2,000',
    sqft: 'Lodge + outdoor terrain',
    ceiling: "Open timber",
    desc: 'Olympic legacy biathlon and cross-country venue in Heber Valley. The lodge, meadow, and sweeping Wasatch views make it a stunning backdrop for outdoor festivals and team-building events.',
  },
  {
    id: 'high-west-distillery',
    name: 'High West Distillery',
    city: 'Wanship, UT',
    region: 'mountain',
    address: '27649 Old Lincoln Hwy, Wanship, UT 84017',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/HighWest.jpg',
    style: 'Distillery & Event Space',
    capacity: '250',
    sqft: '8,000 sq ft',
    ceiling: "Barrel-house loft",
    desc: "Award-winning craft distillery perched above Parley's Canyon. Reclaimed wood, copper stills, and canyon views set a premium backdrop for brand dinners and incentive events.",
  },
  {
    id: 'sundance',
    name: 'Sundance Mountain Resort',
    city: 'Sundance, UT',
    region: 'mountain',
    address: 'N Fork Rd 8841, Sundance, UT 84604',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/Sundance.jpeg',
    style: 'Mountain Resort',
    capacity: '450',
    sqft: 'Tree Room + decks',
    ceiling: 'Open timber',
    desc: "Robert Redford's artist-driven retreat at the base of Mount Timpanogos. Multiple intimate venues spread across a creek-side campus.",
  },

  // ── PARK CITY / DEER VALLEY ─────────────────────────────────
  {
    id: 'grand-hyatt-deer-valley',
    name: 'Grand Hyatt Deer Valley',
    city: 'Park City, UT',
    region: 'mountain',
    address: '1702 Glencoe Mountain Way, Park City, UT 84060',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/GrandHyattDeerValley.jpg',
    style: 'Luxury Mountain Resort',
    capacity: '800',
    sqft: '30,000 sq ft',
    ceiling: "24' great room",
    desc: "Brand-new slopeside resort at Deer Valley's East Village. Expansive ballrooms, rooftop terraces, and true ski-in/ski-out access — setting a new standard for mountain event hospitality.",
  },
  {
    id: 'deer-valley-resort',
    name: 'Deer Valley Resort',
    city: 'Park City, UT',
    region: 'mountain',
    address: '2250 Deer Valley Drive South, Park City, UT 84060',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/DeerValleyResort.jpg',
    style: 'Ski Resort',
    capacity: '1,200',
    sqft: 'Mid-mountain + Snow Park Lodge',
    ceiling: "Timber great room",
    desc: 'The crown jewel of Utah skiing, rated #1 resort in North America. Multiple mid-mountain and base lodges host everything from chairlift-arrival receptions to gala dinners with Wasatch panoramas.',
  },
  {
    id: 'montage-deer-valley',
    name: 'Montage Deer Valley',
    city: 'Park City, UT',
    region: 'mountain',
    address: '9100 Marsac Ave, Park City, UT 84060',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/MontageDeerValley.jpeg',
    style: 'Mountain Resort',
    capacity: '650',
    sqft: '22,000 sq ft',
    ceiling: "20'",
    desc: 'Empire Pass mountain resort with the largest ballroom in Park City. We rig and floral the Empire Ballroom for galas and conferences nationally.',
  },
  {
    id: 'st-regis-deer-valley',
    name: 'St. Regis Deer Valley',
    city: 'Park City, UT',
    region: 'mountain',
    address: '2300 Deer Valley Dr E, Park City, UT 84060',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/StRegisDeerValley.jpg',
    style: 'Mountain Resort',
    capacity: '400',
    sqft: '14,000 sq ft indoor + decks',
    ceiling: "18' great room",
    desc: "Slope-side luxury with a vaulted great room, multiple terraces, and unforgettable winter views. We've produced executive retreats and weddings here through every season.",
  },
  {
    id: 'pendry-park-city',
    name: 'Pendry Park City',
    city: 'Park City, UT',
    region: 'mountain',
    address: '2417 W High Mountain Rd, Park City, UT 84098',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/PendryParkCity.jpg',
    style: 'Luxury Resort',
    capacity: '500',
    sqft: '22,000 sq ft',
    ceiling: "20' ballroom",
    desc: "Canyons-slope luxury — the newest premier property in Park City. The Canyons Ballroom, rooftop deck, and slope-side terrace deliver a modern resort experience with world-class production access.",
  },
  {
    id: 'canyons-village',
    name: 'Canyons Village at PCMR',
    city: 'Park City, UT',
    region: 'mountain',
    address: '4000 Canyons Resort Dr, Park City, UT 84098',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/CanyonsVillage.jpeg',
    style: 'Resort Village',
    capacity: '2,500',
    sqft: 'Village + base lodges',
    ceiling: "Open plaza + lodges",
    desc: 'A full resort village at the base of Park City Mountain. Gondola-arrival events, outdoor plazas, and multiple lodge venues make this the hub for large-scale mountain gatherings.',
  },
  {
    id: 'waldorf-park-city',
    name: 'Waldorf Astoria Park City',
    city: 'Park City, UT',
    region: 'mountain',
    address: '2100 W Frostwood Blvd, Park City, UT 84098',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/WaldorfParkCity.jpeg',
    style: 'Mountain Resort',
    capacity: '300',
    sqft: '8,200 sq ft',
    ceiling: "16'",
    desc: 'Canyons-side property at the base of the gondola. Polished ballroom, exterior plazas, and a private lounge — strong for incentive trips and brand summits.',
  },
  {
    id: 'stein-eriksen',
    name: 'Stein Eriksen Lodge',
    city: 'Park City, UT',
    region: 'mountain',
    address: '7700 Stein Way, Park City, UT 84060',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/SteinEriksen-scaled.jpg',
    style: 'Mountain Lodge',
    capacity: '350',
    sqft: '10,500 sq ft',
    ceiling: "Vaulted timber",
    desc: 'Norwegian-style mountain lodge with timber-framed ballrooms and Silver Lake views. A perennial favorite for incentive groups and intimate galas.',
  },
  {
    id: 'hotel-park-city',
    name: 'Hotel Park City',
    city: 'Park City, UT',
    region: 'mountain',
    address: '2001 Park Ave, Park City, UT 84060',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/HotelParkCity.jpg',
    style: 'Luxury Hotel',
    capacity: '350',
    sqft: '10,000 sq ft',
    ceiling: "16' ballroom",
    desc: 'All-suite luxury hotel minutes from Main Street and the ski slopes. Intimate ballroom, wraparound deck, and exceptional service make it a top choice for executive retreats and incentive groups.',
  },
  {
    id: 'goldener-hirsch',
    name: 'Goldener Hirsch',
    city: 'Park City, UT',
    region: 'mountain',
    address: '7520 Royal St, Park City, UT 84060',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/GoldenerHirsch.jpg',
    style: 'Alpine Inn',
    capacity: '120',
    sqft: '3,000 sq ft',
    ceiling: "Intimate timber",
    desc: 'Intimate Austrian-style inn nestled in Silver Lake Village at Deer Valley. Fireside dining rooms and a terrace overlooking the slopes create an exclusive setting for small destination events.',
  },
  {
    id: 'kimball-art-center',
    name: 'Kimball Art Center',
    city: 'Park City, UT',
    region: 'mountain',
    address: '1401 Kearns Blvd, Park City, UT 84060',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/KimballArtCenter.jpeg',
    style: 'Arts Venue',
    capacity: '400',
    sqft: '8,000 sq ft',
    ceiling: "Industrial loft",
    desc: 'Contemporary arts center in the heart of Park City. Gallery halls, outdoor sculpture garden, and a unique industrial loft aesthetic — a favorite for Sundance Film Festival activations and brand events.',
  },

  // ── JACKSON HOLE ─────────────────────────────────────────────
  {
    id: 'four-seasons-jackson',
    name: 'Four Seasons Jackson Hole',
    city: 'Jackson, WY',
    region: 'jackson',
    address: '7680 Granite Loop Rd, Teton Village, WY 83025',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/JacksonFourSeasons.jpg',
    style: 'Mountain Resort',
    capacity: '500',
    sqft: '12,000 sq ft',
    ceiling: "22' great room",
    desc: 'Teton Village luxury, walking distance to the tram. We travel a full crew for incentive groups, brand summits, and destination weddings.',
  },
  {
    id: 'amangani',
    name: 'Amangani',
    city: 'Jackson, WY',
    region: 'jackson',
    address: '5000 N Spring Gulch Rd, Jackson, WY 83001',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/Amangani.jpg',
    style: 'Resort',
    capacity: '180',
    sqft: 'Indoor + butte terrace',
    ceiling: "Stone + glass",
    desc: 'Sandstone resort perched on a butte over Jackson Hole. Intimate scale, cinematic horizon — perfect for executive retreats and small destination events.',
  },
  {
    id: 'jackson-hole-golf',
    name: 'Jackson Hole Golf & Tennis Club',
    city: 'Jackson, WY',
    region: 'jackson',
    address: '5000 N Spring Gulch Rd, Jackson, WY 83001',
    photo: 'https://intheevent.com/wp-content/uploads/2026/05/JacksonHoleGolfAndTennisClub.gif.jpeg',
    style: 'Golf Club & Event Venue',
    capacity: '300',
    sqft: '8,000 sq ft',
    ceiling: "14' clubhouse",
    desc: 'Iconic Robert Trent Jones Jr. course with a stunning clubhouse overlooking the Tetons. Outdoor pavilion, terrace dining, and mountain panoramas make it a top destination for outdoor receptions and incentive groups.',
  },
];

window.VENUES = VENUES;
